/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Candroid;

import java.awt.Desktop;
import java.net.URL;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author the_p
 */
public class GuestMode extends javax.swing.JFrame {
    /**
     * Creates new form GuestMode
     */
    public GuestMode() {
        initComponents();
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
    }
MysqlConnector Datamine=new MysqlConnector();

public void Brand(){
BrandCB.removeAllItems();
ResultSet Data=Datamine.getResultSetFor("Select distinct brand from devices");
    try {
        while (Data.next()) {            
            BrandCB.addItem(Data.getString("brand"));
        }
    } catch (Exception e) {
        }
}
public void Model(){
String Brand=(String) BrandCB.getSelectedItem();
ModelCB.removeAllItems();
ResultSet Data=Datamine.getResultSetFor("Select distinct model from devices where brand='"+Brand+"';");
    try {
        while (Data.next()) {            
            BrandCB.addItem(Data.getString("model"));
        }
    } catch (Exception e) {
        }
}
public void Version(){
String Brand=(String) BrandCB.getSelectedItem();
String Model=(String) ModelCB.getSelectedItem();
ModelCB.removeAllItems();
ResultSet Data=Datamine.getResultSetFor("Select distinct version from devices where brand='"+Brand+"' and model='"+Model+"';");
    try {
        while (Data.next()) {            
            BrandCB.addItem(Data.getString("version"));
        }
    } catch (Exception e) {
        }
}
public void Roms(){
String Brand=(String) BrandCB.getSelectedItem();
String Model=(String) ModelCB.getSelectedItem();
String Version=(String) VersionCB.getSelectedItem();
ModelCB.removeAllItems();
ResultSet Data=Datamine.getResultSetFor("Select distinct version from devices where brand='"+Brand+"' and model='"+Model+"';");
    try {
        while (Data.next()) {            
            BrandCB.addItem(Data.getString("version"));
        }
    } catch (Exception e) {
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        instruct = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        common = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BrandCB = new javax.swing.JComboBox<>();
        ModelCB = new javax.swing.JComboBox<>();
        VersionCB = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        RomsCB = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        RomLinkLB = new javax.swing.JLabel();
        RomPicLB = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(225, 100, 1037, 507));
        setMinimumSize(new java.awt.Dimension(1037, 510));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        instruct.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        instruct.setForeground(new java.awt.Color(121, 172, 69));
        instruct.setText("<html>Welcome Guest User, Here you can see what we are providing in our interface,<br> You can select your respective phone from the given drop down menu<br> and check if we have have what you need.<br> If you like what we have you can Sign up by clicking the button");

        user.setFont(new java.awt.Font("Bauhaus 93", 0, 20)); // NOI18N
        user.setForeground(new java.awt.Color(121, 172, 69));
        user.setText("Welcome Guest User!!");

        common.setBackground(new java.awt.Color(121, 172, 69));
        common.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        common.setForeground(new java.awt.Color(255, 255, 255));
        common.setText("SIGN UP");
        common.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        common.setBorderPainted(false);
        common.setOpaque(false);
        common.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(121, 172, 69));
        jLabel3.setText("Select Phone Brand");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(121, 172, 69));
        jLabel4.setText("Select Model");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(121, 172, 69));
        jLabel5.setText("Android Version");

        BrandCB.setBackground(new java.awt.Color(121, 172, 69));
        BrandCB.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        BrandCB.setForeground(new java.awt.Color(121, 172, 69));
        BrandCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select brand", "google" }));
        BrandCB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BrandCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BrandCBItemStateChanged(evt);
            }
        });

        ModelCB.setBackground(new java.awt.Color(121, 172, 69));
        ModelCB.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        ModelCB.setForeground(new java.awt.Color(121, 172, 69));
        ModelCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ModelCB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ModelCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ModelCBItemStateChanged(evt);
            }
        });

        VersionCB.setBackground(new java.awt.Color(121, 172, 69));
        VersionCB.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        VersionCB.setForeground(new java.awt.Color(121, 172, 69));
        VersionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        VersionCB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VersionCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                VersionCBItemStateChanged(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(121, 172, 69));
        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GO");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(121, 172, 69));
        jLabel12.setText("Select Roms");

        RomsCB.setBackground(new java.awt.Color(121, 172, 69));
        RomsCB.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        RomsCB.setForeground(new java.awt.Color(121, 172, 69));
        RomsCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RomsCB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RomsCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RomsCBItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(instruct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(BrandCB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(65, 65, 65)
                .addComponent(ModelCB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addComponent(common, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(VersionCB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(RomsCB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(instruct, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3))
                    .addComponent(BrandCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4))
                    .addComponent(ModelCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5))
                    .addComponent(VersionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(RomsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(common, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 470);

        jPanel2.setBackground(new java.awt.Color(121, 172, 69));

        RomLinkLB.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        RomLinkLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        RomLinkLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        RomPicLB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ROM Link");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RomPicLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RomLinkLB, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RomLinkLB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RomPicLB, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addGap(78, 78, 78))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(562, 0, 470, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jPanel2.setVisible(true);
String Model,Brand,Version,Roms,TableRomLink,TablePath;
MysqlConnector Datamine = new MysqlConnector();
Model=(String)ModelCB.getSelectedItem();
Brand=(String)BrandCB.getSelectedItem();
Version=(String)VersionCB.getSelectedItem();
Roms=(String)RomsCB.getSelectedItem();
ResultSet Data=Datamine.getResultSetFor("Select Romlink,path from devices where Model='"+Model+"' and Brand='"+Brand+"' and romversion='"+Version+"' and romname='"+Roms+"';");
        try {
            while (Data.next()) {                
               TableRomLink=Data.getString("romlink");
               TablePath=Data.getString("path");
                RomLinkLB.setText(TableRomLink);
                RomPicLB.setIcon(new ImageIcon(TablePath));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void commonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commonActionPerformed
Signup g=new Signup();
g.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_commonActionPerformed

    private void BrandCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BrandCBItemStateChanged
Brand();       // TODO add your handling code here:
    }//GEN-LAST:event_BrandCBItemStateChanged

    private void ModelCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ModelCBItemStateChanged
Model();       // TODO add your handling code here:
    }//GEN-LAST:event_ModelCBItemStateChanged

    private void VersionCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_VersionCBItemStateChanged
Version();        // TODO add your handling code here:
    }//GEN-LAST:event_VersionCBItemStateChanged

    private void RomsCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RomsCBItemStateChanged
Roms();        // TODO add your handling code here:
    }//GEN-LAST:event_RomsCBItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BrandCB;
    private javax.swing.JComboBox<String> ModelCB;
    private javax.swing.JLabel RomLinkLB;
    private javax.swing.JLabel RomPicLB;
    private javax.swing.JComboBox<String> RomsCB;
    private javax.swing.JComboBox<String> VersionCB;
    private javax.swing.JButton common;
    private javax.swing.JLabel instruct;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
